/****************************************************************************
**
** Metadata for mccdll generated by dumpcpp v5.8.0 using
** dumpcpp.exe mccdll_V114_DEMO.dll
** from the type library mccdll_V114_DEMO.dll
**
****************************************************************************/

#define QAX_DUMPCPP_MCCDLL_NOINLINES
#include "mccdll.h"

using namespace mccdll;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[340];
    char stringdata0[2922];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 26, 0),
QT_MOC_LITERAL(1, 27, 9, 0),
QT_MOC_LITERAL(2, 37, 0, 0),
QT_MOC_LITERAL(3, 38, 4, 0),
QT_MOC_LITERAL(4, 43, 6, 0),
QT_MOC_LITERAL(5, 50, 4, 0),
QT_MOC_LITERAL(6, 55, 4, 0),
QT_MOC_LITERAL(7, 60, 15, 0),
QT_MOC_LITERAL(8, 76, 4, 0),
QT_MOC_LITERAL(9, 81, 6, 0),
QT_MOC_LITERAL(10, 88, 4, 0),
QT_MOC_LITERAL(11, 93, 4, 0),
QT_MOC_LITERAL(12, 98, 18, 0),
QT_MOC_LITERAL(13, 117, 7, 0),
QT_MOC_LITERAL(14, 125, 13, 0),
QT_MOC_LITERAL(15, 139, 11, 0),
QT_MOC_LITERAL(16, 151, 10, 0),
QT_MOC_LITERAL(17, 162, 3, 0),
QT_MOC_LITERAL(18, 166, 26, 0),
QT_MOC_LITERAL(19, 193, 13, 0),
QT_MOC_LITERAL(20, 207, 13, 0),
QT_MOC_LITERAL(21, 221, 4, 0),
QT_MOC_LITERAL(22, 226, 1, 0),
QT_MOC_LITERAL(23, 228, 9, 0),
QT_MOC_LITERAL(24, 238, 1, 0),
QT_MOC_LITERAL(25, 240, 8, 0),
QT_MOC_LITERAL(26, 249, 7, 0),
QT_MOC_LITERAL(27, 257, 3, 0),
QT_MOC_LITERAL(28, 261, 8, 0),
QT_MOC_LITERAL(29, 270, 20, 0),
QT_MOC_LITERAL(30, 291, 11, 0),
QT_MOC_LITERAL(31, 303, 16, 0),
QT_MOC_LITERAL(32, 320, 17, 0),
QT_MOC_LITERAL(33, 338, 16, 0),
QT_MOC_LITERAL(34, 355, 21, 0),
QT_MOC_LITERAL(35, 377, 11, 0),
QT_MOC_LITERAL(36, 389, 12, 0),
QT_MOC_LITERAL(37, 402, 22, 0),
QT_MOC_LITERAL(38, 425, 8, 0),
QT_MOC_LITERAL(39, 434, 7, 0),
QT_MOC_LITERAL(40, 442, 4, 0),
QT_MOC_LITERAL(41, 447, 4, 0),
QT_MOC_LITERAL(42, 452, 11, 0),
QT_MOC_LITERAL(43, 464, 8, 0),
QT_MOC_LITERAL(44, 473, 8, 0),
QT_MOC_LITERAL(45, 482, 13, 0),
QT_MOC_LITERAL(46, 496, 18, 0),
QT_MOC_LITERAL(47, 515, 12, 0),
QT_MOC_LITERAL(48, 528, 11, 0),
QT_MOC_LITERAL(49, 540, 3, 0),
QT_MOC_LITERAL(50, 544, 14, 0),
QT_MOC_LITERAL(51, 559, 11, 0),
QT_MOC_LITERAL(52, 571, 17, 0),
QT_MOC_LITERAL(53, 589, 14, 0),
QT_MOC_LITERAL(54, 604, 20, 0),
QT_MOC_LITERAL(55, 625, 17, 0),
QT_MOC_LITERAL(56, 643, 17, 0),
QT_MOC_LITERAL(57, 661, 14, 0),
QT_MOC_LITERAL(58, 676, 17, 0),
QT_MOC_LITERAL(59, 694, 14, 0),
QT_MOC_LITERAL(60, 709, 17, 0),
QT_MOC_LITERAL(61, 727, 14, 0),
QT_MOC_LITERAL(62, 742, 12, 0),
QT_MOC_LITERAL(63, 755, 9, 0),
QT_MOC_LITERAL(64, 765, 15, 0),
QT_MOC_LITERAL(65, 781, 12, 0),
QT_MOC_LITERAL(66, 794, 19, 0),
QT_MOC_LITERAL(67, 814, 8, 0),
QT_MOC_LITERAL(68, 823, 5, 0),
QT_MOC_LITERAL(69, 829, 13, 0),
QT_MOC_LITERAL(70, 843, 10, 0),
QT_MOC_LITERAL(71, 854, 18, 0),
QT_MOC_LITERAL(72, 873, 12, 0),
QT_MOC_LITERAL(73, 886, 17, 0),
QT_MOC_LITERAL(74, 904, 11, 0),
QT_MOC_LITERAL(75, 916, 7, 0),
QT_MOC_LITERAL(76, 924, 7, 0),
QT_MOC_LITERAL(77, 932, 15, 0),
QT_MOC_LITERAL(78, 948, 5, 0),
QT_MOC_LITERAL(79, 954, 18, 0),
QT_MOC_LITERAL(80, 973, 16, 0),
QT_MOC_LITERAL(81, 990, 3, 0),
QT_MOC_LITERAL(82, 994, 12, 0),
QT_MOC_LITERAL(83, 1007, 1, 0),
QT_MOC_LITERAL(84, 1009, 15, 0),
QT_MOC_LITERAL(85, 1025, 12, 0),
QT_MOC_LITERAL(86, 1038, 10, 0),
QT_MOC_LITERAL(87, 1049, 7, 0),
QT_MOC_LITERAL(88, 1057, 7, 0),
QT_MOC_LITERAL(89, 1065, 25, 0),
QT_MOC_LITERAL(90, 1091, 16, 0),
QT_MOC_LITERAL(91, 1108, 4, 0),
QT_MOC_LITERAL(92, 1113, 7, 0),
QT_MOC_LITERAL(93, 1121, 1, 0),
QT_MOC_LITERAL(94, 1123, 1, 0),
QT_MOC_LITERAL(95, 1125, 1, 0),
QT_MOC_LITERAL(96, 1127, 1, 0),
QT_MOC_LITERAL(97, 1129, 1, 0),
QT_MOC_LITERAL(98, 1131, 1, 0),
QT_MOC_LITERAL(99, 1133, 2, 0),
QT_MOC_LITERAL(100, 1136, 2, 0),
QT_MOC_LITERAL(101, 1139, 2, 0),
QT_MOC_LITERAL(102, 1142, 4, 0),
QT_MOC_LITERAL(103, 1147, 4, 0),
QT_MOC_LITERAL(104, 1152, 4, 0),
QT_MOC_LITERAL(105, 1157, 4, 0),
QT_MOC_LITERAL(106, 1162, 4, 0),
QT_MOC_LITERAL(107, 1167, 4, 0),
QT_MOC_LITERAL(108, 1172, 2, 0),
QT_MOC_LITERAL(109, 1175, 2, 0),
QT_MOC_LITERAL(110, 1178, 2, 0),
QT_MOC_LITERAL(111, 1181, 2, 0),
QT_MOC_LITERAL(112, 1184, 2, 0),
QT_MOC_LITERAL(113, 1187, 2, 0),
QT_MOC_LITERAL(114, 1190, 4, 0),
QT_MOC_LITERAL(115, 1195, 12, 0),
QT_MOC_LITERAL(116, 1208, 4, 0),
QT_MOC_LITERAL(117, 1213, 2, 0),
QT_MOC_LITERAL(118, 1216, 2, 0),
QT_MOC_LITERAL(119, 1219, 2, 0),
QT_MOC_LITERAL(120, 1222, 2, 0),
QT_MOC_LITERAL(121, 1225, 2, 0),
QT_MOC_LITERAL(122, 1228, 2, 0),
QT_MOC_LITERAL(123, 1231, 2, 0),
QT_MOC_LITERAL(124, 1234, 2, 0),
QT_MOC_LITERAL(125, 1237, 3, 0),
QT_MOC_LITERAL(126, 1241, 4, 0),
QT_MOC_LITERAL(127, 1246, 5, 0),
QT_MOC_LITERAL(128, 1252, 4, 0),
QT_MOC_LITERAL(129, 1257, 4, 0),
QT_MOC_LITERAL(130, 1262, 3, 0),
QT_MOC_LITERAL(131, 1266, 3, 0),
QT_MOC_LITERAL(132, 1270, 3, 0),
QT_MOC_LITERAL(133, 1274, 2, 0),
QT_MOC_LITERAL(134, 1277, 2, 0),
QT_MOC_LITERAL(135, 1280, 3, 0),
QT_MOC_LITERAL(136, 1284, 6, 0),
QT_MOC_LITERAL(137, 1291, 9, 0),
QT_MOC_LITERAL(138, 1301, 8, 0),
QT_MOC_LITERAL(139, 1310, 6, 0),
QT_MOC_LITERAL(140, 1317, 7, 0),
QT_MOC_LITERAL(141, 1325, 7, 0),
QT_MOC_LITERAL(142, 1333, 7, 0),
QT_MOC_LITERAL(143, 1341, 7, 0),
QT_MOC_LITERAL(144, 1349, 7, 0),
QT_MOC_LITERAL(145, 1357, 7, 0),
QT_MOC_LITERAL(146, 1365, 7, 0),
QT_MOC_LITERAL(147, 1373, 7, 0),
QT_MOC_LITERAL(148, 1381, 7, 0),
QT_MOC_LITERAL(149, 1389, 7, 0),
QT_MOC_LITERAL(150, 1397, 7, 0),
QT_MOC_LITERAL(151, 1405, 7, 0),
QT_MOC_LITERAL(152, 1413, 7, 0),
QT_MOC_LITERAL(153, 1421, 7, 0),
QT_MOC_LITERAL(154, 1429, 7, 0),
QT_MOC_LITERAL(155, 1437, 7, 0),
QT_MOC_LITERAL(156, 1445, 7, 0),
QT_MOC_LITERAL(157, 1453, 7, 0),
QT_MOC_LITERAL(158, 1461, 7, 0),
QT_MOC_LITERAL(159, 1469, 7, 0),
QT_MOC_LITERAL(160, 1477, 7, 0),
QT_MOC_LITERAL(161, 1485, 7, 0),
QT_MOC_LITERAL(162, 1493, 7, 0),
QT_MOC_LITERAL(163, 1501, 7, 0),
QT_MOC_LITERAL(164, 1509, 7, 0),
QT_MOC_LITERAL(165, 1517, 7, 0),
QT_MOC_LITERAL(166, 1525, 7, 0),
QT_MOC_LITERAL(167, 1533, 8, 0),
QT_MOC_LITERAL(168, 1542, 10, 0),
QT_MOC_LITERAL(169, 1553, 10, 0),
QT_MOC_LITERAL(170, 1564, 10, 0),
QT_MOC_LITERAL(171, 1575, 11, 0),
QT_MOC_LITERAL(172, 1587, 9, 0),
QT_MOC_LITERAL(173, 1597, 9, 0),
QT_MOC_LITERAL(174, 1607, 9, 0),
QT_MOC_LITERAL(175, 1617, 8, 0),
QT_MOC_LITERAL(176, 1626, 8, 0),
QT_MOC_LITERAL(177, 1635, 9, 0),
QT_MOC_LITERAL(178, 1645, 9, 0),
QT_MOC_LITERAL(179, 1655, 6, 0),
QT_MOC_LITERAL(180, 1662, 10, 0),
QT_MOC_LITERAL(181, 1673, 7, 0),
QT_MOC_LITERAL(182, 1681, 10, 0),
QT_MOC_LITERAL(183, 1692, 7, 0),
QT_MOC_LITERAL(184, 1700, 8, 0),
QT_MOC_LITERAL(185, 1709, 5, 0),
QT_MOC_LITERAL(186, 1715, 11, 0),
QT_MOC_LITERAL(187, 1727, 8, 0),
QT_MOC_LITERAL(188, 1736, 15, 0),
QT_MOC_LITERAL(189, 1752, 21, 0),
QT_MOC_LITERAL(190, 1774, 7, 0),
QT_MOC_LITERAL(191, 1782, 8, 0),
QT_MOC_LITERAL(192, 1791, 8, 0),
QT_MOC_LITERAL(193, 1800, 8, 0),
QT_MOC_LITERAL(194, 1809, 7, 0),
QT_MOC_LITERAL(195, 1817, 7, 0),
QT_MOC_LITERAL(196, 1825, 7, 0),
QT_MOC_LITERAL(197, 1833, 7, 0),
QT_MOC_LITERAL(198, 1841, 7, 0),
QT_MOC_LITERAL(199, 1849, 7, 0),
QT_MOC_LITERAL(200, 1857, 8, 0),
QT_MOC_LITERAL(201, 1866, 8, 0),
QT_MOC_LITERAL(202, 1875, 8, 0),
QT_MOC_LITERAL(203, 1884, 7, 0),
QT_MOC_LITERAL(204, 1892, 7, 0),
QT_MOC_LITERAL(205, 1900, 7, 0),
QT_MOC_LITERAL(206, 1908, 7, 0),
QT_MOC_LITERAL(207, 1916, 7, 0),
QT_MOC_LITERAL(208, 1924, 7, 0),
QT_MOC_LITERAL(209, 1932, 7, 0),
QT_MOC_LITERAL(210, 1940, 7, 0),
QT_MOC_LITERAL(211, 1948, 7, 0),
QT_MOC_LITERAL(212, 1956, 7, 0),
QT_MOC_LITERAL(213, 1964, 7, 0),
QT_MOC_LITERAL(214, 1972, 7, 0),
QT_MOC_LITERAL(215, 1980, 7, 0),
QT_MOC_LITERAL(216, 1988, 7, 0),
QT_MOC_LITERAL(217, 1996, 7, 0),
QT_MOC_LITERAL(218, 2004, 7, 0),
QT_MOC_LITERAL(219, 2012, 2, 0),
QT_MOC_LITERAL(220, 2015, 2, 0),
QT_MOC_LITERAL(221, 2018, 2, 0),
QT_MOC_LITERAL(222, 2021, 2, 0),
QT_MOC_LITERAL(223, 2024, 2, 0),
QT_MOC_LITERAL(224, 2027, 2, 0),
QT_MOC_LITERAL(225, 2030, 5, 0),
QT_MOC_LITERAL(226, 2036, 6, 0),
QT_MOC_LITERAL(227, 2043, 7, 0),
QT_MOC_LITERAL(228, 2051, 7, 0),
QT_MOC_LITERAL(229, 2059, 9, 0),
QT_MOC_LITERAL(230, 2069, 13, 0),
QT_MOC_LITERAL(231, 2083, 8, 0),
QT_MOC_LITERAL(232, 2092, 7, 0),
QT_MOC_LITERAL(233, 2100, 4, 0),
QT_MOC_LITERAL(234, 2105, 8, 0),
QT_MOC_LITERAL(235, 2114, 5, 0),
QT_MOC_LITERAL(236, 2120, 7, 0),
QT_MOC_LITERAL(237, 2128, 4, 0),
QT_MOC_LITERAL(238, 2133, 9, 0),
QT_MOC_LITERAL(239, 2143, 6, 0),
QT_MOC_LITERAL(240, 2150, 7, 0),
QT_MOC_LITERAL(241, 2158, 4, 0),
QT_MOC_LITERAL(242, 2163, 11, 0),
QT_MOC_LITERAL(243, 2175, 8, 0),
QT_MOC_LITERAL(244, 2184, 10, 0),
QT_MOC_LITERAL(245, 2195, 7, 0),
QT_MOC_LITERAL(246, 2203, 12, 0),
QT_MOC_LITERAL(247, 2216, 9, 0),
QT_MOC_LITERAL(248, 2226, 20, 0),
QT_MOC_LITERAL(249, 2247, 16, 0),
QT_MOC_LITERAL(250, 2264, 8, 0),
QT_MOC_LITERAL(251, 2273, 7, 0),
QT_MOC_LITERAL(252, 2281, 2, 0),
QT_MOC_LITERAL(253, 2284, 2, 0),
QT_MOC_LITERAL(254, 2287, 6, 0),
QT_MOC_LITERAL(255, 2294, 8, 0),
QT_MOC_LITERAL(256, 2303, 6, 0),
QT_MOC_LITERAL(257, 2310, 8, 0),
QT_MOC_LITERAL(258, 2319, 9, 0),
QT_MOC_LITERAL(259, 2329, 9, 0),
QT_MOC_LITERAL(260, 2339, 6, 0),
QT_MOC_LITERAL(261, 2346, 7, 0),
QT_MOC_LITERAL(262, 2354, 6, 0),
QT_MOC_LITERAL(263, 2361, 9, 0),
QT_MOC_LITERAL(264, 2371, 6, 0),
QT_MOC_LITERAL(265, 2378, 15, 0),
QT_MOC_LITERAL(266, 2394, 20, 0),
QT_MOC_LITERAL(267, 2415, 10, 0),
QT_MOC_LITERAL(268, 2426, 3, 0),
QT_MOC_LITERAL(269, 2430, 3, 0),
QT_MOC_LITERAL(270, 2434, 3, 0),
QT_MOC_LITERAL(271, 2438, 2, 0),
QT_MOC_LITERAL(272, 2441, 2, 0),
QT_MOC_LITERAL(273, 2444, 2, 0),
QT_MOC_LITERAL(274, 2447, 2, 0),
QT_MOC_LITERAL(275, 2450, 2, 0),
QT_MOC_LITERAL(276, 2453, 2, 0),
QT_MOC_LITERAL(277, 2456, 3, 0),
QT_MOC_LITERAL(278, 2460, 3, 0),
QT_MOC_LITERAL(279, 2464, 3, 0),
QT_MOC_LITERAL(280, 2468, 3, 0),
QT_MOC_LITERAL(281, 2472, 3, 0),
QT_MOC_LITERAL(282, 2476, 3, 0),
QT_MOC_LITERAL(283, 2480, 2, 0),
QT_MOC_LITERAL(284, 2483, 2, 0),
QT_MOC_LITERAL(285, 2486, 3, 0),
QT_MOC_LITERAL(286, 2490, 3, 0),
QT_MOC_LITERAL(287, 2494, 4, 0),
QT_MOC_LITERAL(288, 2499, 4, 0),
QT_MOC_LITERAL(289, 2504, 4, 0),
QT_MOC_LITERAL(290, 2509, 4, 0),
QT_MOC_LITERAL(291, 2514, 4, 0),
QT_MOC_LITERAL(292, 2519, 4, 0),
QT_MOC_LITERAL(293, 2524, 4, 0),
QT_MOC_LITERAL(294, 2529, 2, 0),
QT_MOC_LITERAL(295, 2532, 5, 0),
QT_MOC_LITERAL(296, 2538, 5, 0),
QT_MOC_LITERAL(297, 2544, 5, 0),
QT_MOC_LITERAL(298, 2550, 4, 0),
QT_MOC_LITERAL(299, 2555, 4, 0),
QT_MOC_LITERAL(300, 2560, 4, 0),
QT_MOC_LITERAL(301, 2565, 3, 0),
QT_MOC_LITERAL(302, 2569, 3, 0),
QT_MOC_LITERAL(303, 2573, 4, 0),
QT_MOC_LITERAL(304, 2578, 4, 0),
QT_MOC_LITERAL(305, 2583, 3, 0),
QT_MOC_LITERAL(306, 2587, 3, 0),
QT_MOC_LITERAL(307, 2591, 3, 0),
QT_MOC_LITERAL(308, 2595, 3, 0),
QT_MOC_LITERAL(309, 2599, 3, 0),
QT_MOC_LITERAL(310, 2603, 3, 0),
QT_MOC_LITERAL(311, 2607, 5, 0),
QT_MOC_LITERAL(312, 2613, 4, 0),
QT_MOC_LITERAL(313, 2618, 11, 0),
QT_MOC_LITERAL(314, 2630, 7, 0),
QT_MOC_LITERAL(315, 2638, 4, 0),
QT_MOC_LITERAL(316, 2643, 8, 0),
QT_MOC_LITERAL(317, 2652, 5, 0),
QT_MOC_LITERAL(318, 2658, 7, 0),
QT_MOC_LITERAL(319, 2666, 4, 0),
QT_MOC_LITERAL(320, 2671, 19, 0),
QT_MOC_LITERAL(321, 2691, 20, 0),
QT_MOC_LITERAL(322, 2712, 10, 0),
QT_MOC_LITERAL(323, 2723, 8, 0),
QT_MOC_LITERAL(324, 2732, 10, 0),
QT_MOC_LITERAL(325, 2743, 10, 0),
QT_MOC_LITERAL(326, 2754, 10, 0),
QT_MOC_LITERAL(327, 2765, 10, 0),
QT_MOC_LITERAL(328, 2776, 10, 0),
QT_MOC_LITERAL(329, 2787, 10, 0),
QT_MOC_LITERAL(330, 2798, 10, 0),
QT_MOC_LITERAL(331, 2809, 10, 0),
QT_MOC_LITERAL(332, 2820, 10, 0),
QT_MOC_LITERAL(333, 2831, 11, 0),
QT_MOC_LITERAL(334, 2843, 11, 0),
QT_MOC_LITERAL(335, 2855, 11, 0),
QT_MOC_LITERAL(336, 2867, 8, 0),
QT_MOC_LITERAL(337, 2876, 14, 0),
QT_MOC_LITERAL(338, 2891, 9, 0),
QT_MOC_LITERAL(339, 2901, 19, 0)
    },
    "mccdll::_MotionControlCard\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0CancelSpeedControl\0AxisNum\0ClearAutoText\0ClearBuffer\0"
    "GetActualF\0Typ\0GetActualMachineCoordinate\0GetCodeLength\0GetCodeRunNow\0int&\0"
    "p\0GetFvalue\0n\0GetGmode\0GetIOin\0num\0GetIOout\0GetMachineCoordinate\0GetMultiple\0"
    "GetParameterText\0GetParameterValue\0GetRefCoordinate\0GetSpindleInformation\0"
    "GetWorkMode\0GetWorkState\0GetWorkpieceCoordinate\0Ini_card\0Move_XY\0axis\0valu\0"
    "OpenProgram\0QString&\0FileName\0Open_ParaForm\0SaveParameterValue\0SendAutoText\0"
    "SendMDItext\0txt\0SetAutoRunFlag\0AutoRunFlag\0SetClosedControlA\0ClosedControlA\0"
    "SetClosedControlFlag\0ClosedControlFlag\0SetClosedControlX\0ClosedControlX\0"
    "SetClosedControlY\0ClosedControlY\0SetClosedControlZ\0ClosedControlZ\0SetFeedBLnow\0"
    "FeedBLnow\0SetFeedrateFlag\0FeedrateFlag\0SetFeedrateMultiple\0SetIOout\0value\0"
    "SetIniPnowFlg\0IniPnowFlg\0SetInitialPosition\0SetParameter\0SetParameterValue\0"
    "SetSeekZero\0double&\0Baizhen\0SetSpeedControl\0Speed\0SetSpindleMultiple\0"
    "SetSpindleRotate\0SPR\0SetStartline\0L\0SetStepStopFlag\0StepStopFlag\0SetVersion\0"
    "Version\0control\0mccdll::MotionControlCard\0mccdll::_Explain\0Expl\0Explain\0X\0Y\0"
    "Z\0a\0b\0c\0ox\0oy\0oz\0xend\0yend\0zend\0aend\0bend\0cend\0xr\0yr\0zr\0ar\0br\0cr\0text\0"
    "QStringList&\0mode\0CF\0af\0f0\0F1\0F2\0F3\0F4\0F5\0acc\0Snow\0g68an\0G681\0G682\0Hbx\0Hby\0"
    "Hbz\0Db\0Ds\0Dan\0Export\0M_EO_Type\0M_EO_num\0M_EO_F\0M_EO_F0\0M_EO_F1\0M_EO_F2\0M_EO_F3\0"
    "M_EO_F4\0M_EO_F5\0M_EO_x0\0M_EO_y0\0M_EO_z0\0M_EO_a0\0M_EO_b0\0M_EO_c0\0M_EO_x1\0"
    "M_EO_y1\0M_EO_z1\0M_EO_a1\0M_EO_b1\0M_EO_c1\0M_EO_ox\0M_EO_oy\0M_EO_oz\0M_EO_xr\0"
    "M_EO_yr\0M_EO_zr\0M_EO_ar\0M_EO_br\0M_EO_cr\0M_EO_txt\0M_EO_mode1\0M_EO_G6801\0"
    "M_EO_G6802\0M_EO_G68ang\0M_EO_hbbz\0M_EO_hbbx\0M_EO_hbby\0M_EO_dbb\0M_EO_dss\0"
    "M_EO_dann\0SetFchflg\0Fchflg\0SetFchflg2\0Fchflg2\0SetJumpFlg\0JumpFlg\0SetKongF\0"
    "KongF\0SetVarChFlg\0VarChFlg\0mccdll::Explain\0mccdll::_Interpolator\0Cal_arc\0"
    "M_CA_seg\0M_CA_typ\0M_CA_pla\0M_CA_xp\0M_CA_yp\0M_CA_zp\0M_CA_x0\0M_CA_y0\0M_CA_z0\0"
    "M_CA_xx1\0M_CA_yy1\0M_CA_zz1\0M_CA_ox\0M_CA_oy\0M_CA_oz\0Cal_cos\0M_CC_xp\0M_CC_yp\0"
    "M_CC_zp\0M_CC_ap\0M_CC_bp\0M_CC_cp\0M_CC_x1\0M_CC_y1\0M_CC_z1\0M_CC_a1\0M_CC_b1\0"
    "M_CC_c1\0x0\0y0\0z0\0a0\0b0\0c0\0Cal_s\0M_CS_i\0M_CS_vb\0M_CS_ve\0Calculate\0Interpolation\0"
    "Pretreat\0SetAcce\0Acce\0SetCHxsh\0CHxsh\0SetF_bl\0F_bl\0SetG0F_bl\0G0F_bl\0SetJerk\0"
    "Jerk\0SetPointNum\0PointNum\0SetSSegFlg\0SSegFlg\0SetSegEndnum\0SegEndnum\0"
    "mccdll::Interpolator\0mccdll::_Gincode\0BaseCode\0DealM98\0n0\0n1\0ExpOut\0M_EX_seg\0"
    "Inport\0codeline\0MDIinport\0Setsegnow\0M_SE_i\0ShowOut\0M_SH_i\0setLength\0length\0"
    "mccdll::Gincode\0mccdll::_PointBuffer\0ControlOut\0xxo\0yyo\0zzo\0xe\0ye\0ze\0ae\0be\0"
    "ce\0xrr\0yrr\0zrr\0arr\0brr\0crr\0tt\0nn\0inf\0acf\0inf0\0inf1\0inf2\0inf3\0inf4\0inf5\0leng\0"
    "sn\0g6811\0g6822\0g68aa\0hbbz\0hbbx\0hbby\0dbb\0dss\0dann\0Load\0xre\0yre\0zre\0are\0bre\0"
    "cre\0segty\0segn\0PointBuffer\0setHead\0head\0setHeadf\0headf\0setTail\0tail\0"
    "mccdll::PointBuffer\0mccdll::_Instruction\0InputInstr\0M_IP_Typ\0M_IP_para1\0"
    "M_IP_para2\0M_IP_para3\0M_IP_para4\0M_IP_para5\0M_IP_para6\0M_IP_para7\0M_IP_para8\0"
    "M_IP_para9\0M_IP_para10\0Instruction\0OutputInstr\0M_OU_Typ\0QVariantList*&\0"
    "M_OU_para\0mccdll::Instruction\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_mccdll___MotionControlCard[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    55, 14, // methods
    12, 456, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 289, 2, 5,
    7, 1, 298, 2, 5,
    9, 3, 301, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 308, 2, 9,
    14, 0, 311, 2, 9,
    15, 0, 312, 2, 9,
    16, 1, 313, 2, 9,
    18, 1, 316, 2, 9,
    19, 0, 319, 2, 9,
    20, 0, 320, 2, 11,
    20, 1, 321, 2, 9,
    23, 0, 324, 2, 11,
    23, 1, 325, 2, 9,
    25, 1, 328, 2, 9,
    26, 1, 331, 2, 9,
    28, 1, 334, 2, 9,
    29, 1, 337, 2, 9,
    30, 1, 340, 2, 9,
    31, 1, 343, 2, 9,
    32, 1, 346, 2, 9,
    33, 1, 349, 2, 9,
    34, 1, 352, 2, 9,
    35, 0, 355, 2, 9,
    36, 0, 356, 2, 9,
    37, 1, 357, 2, 9,
    38, 0, 360, 2, 9,
    39, 2, 361, 2, 9,
    42, 1, 366, 2, 9,
    45, 0, 369, 2, 11,
    45, 1, 370, 2, 9,
    46, 0, 373, 2, 9,
    47, 1, 374, 2, 9,
    48, 1, 377, 2, 9,
    50, 1, 380, 2, 9,
    52, 1, 383, 2, 9,
    54, 1, 386, 2, 9,
    56, 1, 389, 2, 9,
    58, 1, 392, 2, 9,
    60, 1, 395, 2, 9,
    62, 1, 398, 2, 9,
    64, 1, 401, 2, 9,
    66, 1, 404, 2, 9,
    67, 2, 407, 2, 9,
    69, 1, 412, 2, 9,
    71, 0, 415, 2, 9,
    72, 3, 416, 2, 9,
    73, 2, 423, 2, 9,
    74, 1, 428, 2, 11,
    74, 2, 431, 2, 9,
    77, 2, 436, 2, 9,
    79, 1, 441, 2, 9,
    80, 1, 444, 2, 9,
    82, 1, 447, 2, 9,
    84, 1, 450, 2, 9,
    86, 1, 453, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 17,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::QString, 0x80000000 | 21, 22,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 21, 24,
    QMetaType::QString, QMetaType::Int, 24,
    QMetaType::Int, QMetaType::Int, 27,
    QMetaType::Int, QMetaType::Int, 27,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Int, QMetaType::Int, 17,
    QMetaType::QString, QMetaType::Int, 27,
    QMetaType::Double, QMetaType::Int, 27,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Int, QMetaType::Int, 17,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 40, 41,
    QMetaType::Void, 0x80000000 | 43, 44,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 24,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 43, 3,
    QMetaType::Void, 0x80000000 | 43, 49,
    QMetaType::Void, QMetaType::Bool, 51,
    QMetaType::Void, QMetaType::Bool, 53,
    QMetaType::Void, QMetaType::Bool, 55,
    QMetaType::Void, QMetaType::Bool, 57,
    QMetaType::Void, QMetaType::Bool, 59,
    QMetaType::Void, QMetaType::Bool, 61,
    QMetaType::Void, QMetaType::Int, 63,
    QMetaType::Void, QMetaType::Bool, 65,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 27, 68,
    QMetaType::Void, QMetaType::Int, 70,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, QMetaType::QString, 27, 68, 49,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 27, 68,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 75, 13, 76,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 13, 78,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 81,
    QMetaType::Void, 0x80000000 | 21, 83,
    QMetaType::Void, QMetaType::Bool, 85,
    QMetaType::Void, QMetaType::QString, 87,

 // properties: name, type, flags
    51, QMetaType::Bool, 0x01015003, 		 // bool AutoRunFlag
    53, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlA
    55, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlFlag
    57, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlX
    59, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlY
    61, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlZ
    63, QMetaType::Int, 0x02015003, 		 // int FeedBLnow
    65, QMetaType::Bool, 0x01015003, 		 // bool FeedrateFlag
    70, QMetaType::Int, 0x02015003, 		 // int IniPnowFlg
    85, QMetaType::Bool, 0x01015003, 		 // bool StepStopFlag
    87, QMetaType::QString, 0x0a015003, 		 // QString Version
    88, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _MotionControlCard::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll___MotionControlCard, 0, 0, 0 }
};

void *_MotionControlCard::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::_MotionControlCard"))
        return static_cast<void*>(const_cast<_MotionControlCard*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll__MotionControlCard[] = {

 // content:
    7, // revision
    89,  // classname
    0, 0, // classinfo
    55, 14, // methods
    11, 456, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 289, 2, 5,
    7, 1, 298, 2, 5,
    9, 3, 301, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 308, 2, 9,
    14, 0, 311, 2, 9,
    15, 0, 312, 2, 9,
    16, 1, 313, 2, 9,
    18, 1, 316, 2, 9,
    19, 0, 319, 2, 9,
    20, 0, 320, 2, 11,
    20, 1, 321, 2, 9,
    23, 0, 324, 2, 11,
    23, 1, 325, 2, 9,
    25, 1, 328, 2, 9,
    26, 1, 331, 2, 9,
    28, 1, 334, 2, 9,
    29, 1, 337, 2, 9,
    30, 1, 340, 2, 9,
    31, 1, 343, 2, 9,
    32, 1, 346, 2, 9,
    33, 1, 349, 2, 9,
    34, 1, 352, 2, 9,
    35, 0, 355, 2, 9,
    36, 0, 356, 2, 9,
    37, 1, 357, 2, 9,
    38, 0, 360, 2, 9,
    39, 2, 361, 2, 9,
    42, 1, 366, 2, 9,
    45, 0, 369, 2, 11,
    45, 1, 370, 2, 9,
    46, 0, 373, 2, 9,
    47, 1, 374, 2, 9,
    48, 1, 377, 2, 9,
    50, 1, 380, 2, 9,
    52, 1, 383, 2, 9,
    54, 1, 386, 2, 9,
    56, 1, 389, 2, 9,
    58, 1, 392, 2, 9,
    60, 1, 395, 2, 9,
    62, 1, 398, 2, 9,
    64, 1, 401, 2, 9,
    66, 1, 404, 2, 9,
    67, 2, 407, 2, 9,
    69, 1, 412, 2, 9,
    71, 0, 415, 2, 9,
    72, 3, 416, 2, 9,
    73, 2, 423, 2, 9,
    74, 1, 428, 2, 11,
    74, 2, 431, 2, 9,
    77, 2, 436, 2, 9,
    79, 1, 441, 2, 9,
    80, 1, 444, 2, 9,
    82, 1, 447, 2, 9,
    84, 1, 450, 2, 9,
    86, 1, 453, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 17,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::QString, 0x80000000 | 21, 22,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 21, 24,
    QMetaType::QString, QMetaType::Int, 24,
    QMetaType::Int, QMetaType::Int, 27,
    QMetaType::Int, QMetaType::Int, 27,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Int, QMetaType::Int, 17,
    QMetaType::QString, QMetaType::Int, 27,
    QMetaType::Double, QMetaType::Int, 27,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Int, QMetaType::Int, 17,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Double, QMetaType::Int, 17,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 40, 41,
    QMetaType::Void, 0x80000000 | 43, 44,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 24,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 43, 3,
    QMetaType::Void, 0x80000000 | 43, 49,
    QMetaType::Void, QMetaType::Bool, 51,
    QMetaType::Void, QMetaType::Bool, 53,
    QMetaType::Void, QMetaType::Bool, 55,
    QMetaType::Void, QMetaType::Bool, 57,
    QMetaType::Void, QMetaType::Bool, 59,
    QMetaType::Void, QMetaType::Bool, 61,
    QMetaType::Void, QMetaType::Int, 63,
    QMetaType::Void, QMetaType::Bool, 65,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 27, 68,
    QMetaType::Void, QMetaType::Int, 70,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, QMetaType::QString, 27, 68, 49,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 27, 68,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 75, 13, 76,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 13, 78,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 81,
    QMetaType::Void, 0x80000000 | 21, 83,
    QMetaType::Void, QMetaType::Bool, 85,
    QMetaType::Void, QMetaType::QString, 87,

 // properties: name, type, flags
    51, QMetaType::Bool, 0x01015003, 		 // bool AutoRunFlag
    53, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlA
    55, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlFlag
    57, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlX
    59, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlY
    61, QMetaType::Bool, 0x01015003, 		 // bool ClosedControlZ
    63, QMetaType::Int, 0x02015003, 		 // int FeedBLnow
    65, QMetaType::Bool, 0x01015003, 		 // bool FeedrateFlag
    70, QMetaType::Int, 0x02015003, 		 // int IniPnowFlg
    85, QMetaType::Bool, 0x01015003, 		 // bool StepStopFlag
    87, QMetaType::QString, 0x0a015003, 		 // QString Version

    0 // eod
};

const QMetaObject MotionControlCard::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll__MotionControlCard, 0, 0, 0 }
};

void *MotionControlCard::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::MotionControlCard"))
        return static_cast<void*>(const_cast<MotionControlCard*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll___Explain[] = {

 // content:
    7, // revision
    90,  // classname
    0, 0, // classinfo
    11, 14, // methods
    6, 278, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    91, 0, 88, 2, 9,
    92, 45, 89, 2, 9,
    136, 41, 180, 2, 9,
    178, 1, 263, 2, 9,
    180, 1, 266, 2, 9,
    182, 1, 269, 2, 9,
    184, 1, 272, 2, 9,
    186, 1, 275, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Int, QMetaType::QString, 0x80000000 | 115, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 17, 27, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 83, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
    QMetaType::QVariant, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 43, 0x80000000 | 115, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
    QMetaType::Void, QMetaType::Int, 179,
    QMetaType::Void, QMetaType::Int, 181,
    QMetaType::Void, QMetaType::Int, 183,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,

 // properties: name, type, flags
    179, QMetaType::Int, 0x02015003, 		 // int Fchflg
    181, QMetaType::Int, 0x02015003, 		 // int Fchflg2
    183, QMetaType::Int, 0x02015003, 		 // int JumpFlg
    185, QMetaType::Int, 0x02015003, 		 // int KongF
    187, QMetaType::Int, 0x02015003, 		 // int VarChFlg
    88, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _Explain::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll___Explain, 0, 0, 0 }
};

void *_Explain::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::_Explain"))
        return static_cast<void*>(const_cast<_Explain*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll__Explain[] = {

 // content:
    7, // revision
    188,  // classname
    0, 0, // classinfo
    11, 14, // methods
    5, 278, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    91, 0, 88, 2, 9,
    92, 45, 89, 2, 9,
    136, 41, 180, 2, 9,
    178, 1, 263, 2, 9,
    180, 1, 266, 2, 9,
    182, 1, 269, 2, 9,
    184, 1, 272, 2, 9,
    186, 1, 275, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Int, QMetaType::QString, 0x80000000 | 115, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 17, 27, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 83, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
    QMetaType::QVariant, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 43, 0x80000000 | 115, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
    QMetaType::Void, QMetaType::Int, 179,
    QMetaType::Void, QMetaType::Int, 181,
    QMetaType::Void, QMetaType::Int, 183,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,

 // properties: name, type, flags
    179, QMetaType::Int, 0x02015003, 		 // int Fchflg
    181, QMetaType::Int, 0x02015003, 		 // int Fchflg2
    183, QMetaType::Int, 0x02015003, 		 // int JumpFlg
    185, QMetaType::Int, 0x02015003, 		 // int KongF
    187, QMetaType::Int, 0x02015003, 		 // int VarChFlg

    0 // eod
};

const QMetaObject Explain::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll__Explain, 0, 0, 0 }
};

void *Explain::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::Explain"))
        return static_cast<void*>(const_cast<Explain*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll___Interpolator[] = {

 // content:
    7, // revision
    189,  // classname
    0, 0, // classinfo
    17, 14, // methods
    9, 220, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 99, 2, 5,
    7, 1, 108, 2, 5,
    9, 3, 111, 2, 5,

// slot: name, argc, parameters, tag, flags
    190, 15, 118, 2, 9,
    206, 18, 149, 2, 9,
    225, 3, 186, 2, 9,
    229, 0, 193, 2, 9,
    230, 0, 194, 2, 9,
    231, 0, 195, 2, 9,
    232, 1, 196, 2, 9,
    234, 1, 199, 2, 9,
    236, 1, 202, 2, 9,
    238, 1, 205, 2, 9,
    240, 1, 208, 2, 9,
    242, 1, 211, 2, 9,
    244, 1, 214, 2, 9,
    246, 1, 217, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Double, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
    QMetaType::Double, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
    QMetaType::Double, QMetaType::Int, QMetaType::Double, QMetaType::Double, 226, 227, 228,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Double, 233,
    QMetaType::Void, QMetaType::Double, 235,
    QMetaType::Void, QMetaType::Int, 237,
    QMetaType::Void, QMetaType::Int, 239,
    QMetaType::Void, QMetaType::Double, 241,
    QMetaType::Void, QMetaType::Int, 243,
    QMetaType::Void, QMetaType::Int, 245,
    QMetaType::Void, QMetaType::Int, 247,

 // properties: name, type, flags
    233, QMetaType::Double, 0x06015003, 		 // double Acce
    235, QMetaType::Double, 0x06015003, 		 // double CHxsh
    237, QMetaType::Int, 0x02015003, 		 // int F_bl
    239, QMetaType::Int, 0x02015003, 		 // int G0F_bl
    241, QMetaType::Double, 0x06015003, 		 // double Jerk
    243, QMetaType::Int, 0x02015003, 		 // int PointNum
    245, QMetaType::Int, 0x02015003, 		 // int SSegFlg
    247, QMetaType::Int, 0x02015003, 		 // int SegEndnum
    88, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _Interpolator::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll___Interpolator, 0, 0, 0 }
};

void *_Interpolator::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::_Interpolator"))
        return static_cast<void*>(const_cast<_Interpolator*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll__Interpolator[] = {

 // content:
    7, // revision
    248,  // classname
    0, 0, // classinfo
    17, 14, // methods
    8, 220, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 99, 2, 5,
    7, 1, 108, 2, 5,
    9, 3, 111, 2, 5,

// slot: name, argc, parameters, tag, flags
    190, 15, 118, 2, 9,
    206, 18, 149, 2, 9,
    225, 3, 186, 2, 9,
    229, 0, 193, 2, 9,
    230, 0, 194, 2, 9,
    231, 0, 195, 2, 9,
    232, 1, 196, 2, 9,
    234, 1, 199, 2, 9,
    236, 1, 202, 2, 9,
    238, 1, 205, 2, 9,
    240, 1, 208, 2, 9,
    242, 1, 211, 2, 9,
    244, 1, 214, 2, 9,
    246, 1, 217, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Double, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
    QMetaType::Double, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
    QMetaType::Double, QMetaType::Int, QMetaType::Double, QMetaType::Double, 226, 227, 228,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Double, 233,
    QMetaType::Void, QMetaType::Double, 235,
    QMetaType::Void, QMetaType::Int, 237,
    QMetaType::Void, QMetaType::Int, 239,
    QMetaType::Void, QMetaType::Double, 241,
    QMetaType::Void, QMetaType::Int, 243,
    QMetaType::Void, QMetaType::Int, 245,
    QMetaType::Void, QMetaType::Int, 247,

 // properties: name, type, flags
    233, QMetaType::Double, 0x06015003, 		 // double Acce
    235, QMetaType::Double, 0x06015003, 		 // double CHxsh
    237, QMetaType::Int, 0x02015003, 		 // int F_bl
    239, QMetaType::Int, 0x02015003, 		 // int G0F_bl
    241, QMetaType::Double, 0x06015003, 		 // double Jerk
    243, QMetaType::Int, 0x02015003, 		 // int PointNum
    245, QMetaType::Int, 0x02015003, 		 // int SSegFlg
    247, QMetaType::Int, 0x02015003, 		 // int SegEndnum

    0 // eod
};

const QMetaObject Interpolator::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll__Interpolator, 0, 0, 0 }
};

void *Interpolator::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::Interpolator"))
        return static_cast<void*>(const_cast<Interpolator*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll___Gincode[] = {

 // content:
    7, // revision
    249,  // classname
    0, 0, // classinfo
    11, 14, // methods
    2, 116, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    250, 0, 88, 2, 9,
    251, 4, 89, 2, 9,
    254, 1, 98, 2, 9,
    256, 1, 101, 2, 9,
    258, 1, 104, 2, 9,
    259, 1, 107, 2, 9,
    261, 1, 110, 2, 9,
    263, 1, 113, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 27, 252, 253, 22,
    QMetaType::QVariant, 0x80000000 | 21, 255,
    QMetaType::Void, QMetaType::QString, 257,
    QMetaType::Void, QMetaType::QString, 257,
    QMetaType::Void, QMetaType::Int, 260,
    QMetaType::QVariant, QMetaType::Int, 262,
    QMetaType::Void, QMetaType::Int, 264,

 // properties: name, type, flags
    88, QMetaType::QString, 0x0a055003, 		 // QString control
    264, QMetaType::Int, 0x02015003, 		 // int length

    0 // eod
};

const QMetaObject _Gincode::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll___Gincode, 0, 0, 0 }
};

void *_Gincode::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::_Gincode"))
        return static_cast<void*>(const_cast<_Gincode*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll__Gincode[] = {

 // content:
    7, // revision
    265,  // classname
    0, 0, // classinfo
    11, 14, // methods
    1, 116, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    250, 0, 88, 2, 9,
    251, 4, 89, 2, 9,
    254, 1, 98, 2, 9,
    256, 1, 101, 2, 9,
    258, 1, 104, 2, 9,
    259, 1, 107, 2, 9,
    261, 1, 110, 2, 9,
    263, 1, 113, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 27, 252, 253, 22,
    QMetaType::QVariant, 0x80000000 | 21, 255,
    QMetaType::Void, QMetaType::QString, 257,
    QMetaType::Void, QMetaType::QString, 257,
    QMetaType::Void, QMetaType::Int, 260,
    QMetaType::QVariant, QMetaType::Int, 262,
    QMetaType::Void, QMetaType::Int, 264,

 // properties: name, type, flags
    264, QMetaType::Int, 0x02015003, 		 // int length

    0 // eod
};

const QMetaObject Gincode::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll__Gincode, 0, 0, 0 }
};

void *Gincode::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::Gincode"))
        return static_cast<void*>(const_cast<Gincode*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll___PointBuffer[] = {

 // content:
    7, // revision
    266,  // classname
    0, 0, // classinfo
    9, 14, // methods
    4, 266, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 59, 2, 5,
    7, 1, 68, 2, 5,
    9, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    267, 44, 78, 2, 9,
    304, 44, 167, 2, 9,
    313, 0, 256, 2, 9,
    314, 1, 257, 2, 9,
    316, 1, 260, 2, 9,
    318, 1, 263, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::QVariant, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 43, 0x80000000 | 115, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 93, 94, 95, 96, 97, 98, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 49, 116, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
    QMetaType::QVariant, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Int, QMetaType::QString, 0x80000000 | 115, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 93, 94, 95, 96, 97, 98, 268, 269, 270, 271, 272, 273, 274, 275, 276, 305, 306, 307, 308, 309, 310, 311, 312, 49, 116, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 315,
    QMetaType::Void, QMetaType::Int, 317,
    QMetaType::Void, QMetaType::Int, 319,

 // properties: name, type, flags
    88, QMetaType::QString, 0x0a055003, 		 // QString control
    315, QMetaType::Int, 0x02015003, 		 // int head
    317, QMetaType::Int, 0x02015003, 		 // int headf
    319, QMetaType::Int, 0x02015003, 		 // int tail

    0 // eod
};

const QMetaObject _PointBuffer::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll___PointBuffer, 0, 0, 0 }
};

void *_PointBuffer::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::_PointBuffer"))
        return static_cast<void*>(const_cast<_PointBuffer*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll__PointBuffer[] = {

 // content:
    7, // revision
    320,  // classname
    0, 0, // classinfo
    9, 14, // methods
    3, 266, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 59, 2, 5,
    7, 1, 68, 2, 5,
    9, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    267, 44, 78, 2, 9,
    304, 44, 167, 2, 9,
    313, 0, 256, 2, 9,
    314, 1, 257, 2, 9,
    316, 1, 260, 2, 9,
    318, 1, 263, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::QVariant, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 43, 0x80000000 | 115, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 21, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 0x80000000 | 75, 93, 94, 95, 96, 97, 98, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 49, 116, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
    QMetaType::QVariant, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Int, QMetaType::QString, 0x80000000 | 115, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 93, 94, 95, 96, 97, 98, 268, 269, 270, 271, 272, 273, 274, 275, 276, 305, 306, 307, 308, 309, 310, 311, 312, 49, 116, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 315,
    QMetaType::Void, QMetaType::Int, 317,
    QMetaType::Void, QMetaType::Int, 319,

 // properties: name, type, flags
    315, QMetaType::Int, 0x02015003, 		 // int head
    317, QMetaType::Int, 0x02015003, 		 // int headf
    319, QMetaType::Int, 0x02015003, 		 // int tail

    0 // eod
};

const QMetaObject PointBuffer::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll__PointBuffer, 0, 0, 0 }
};

void *PointBuffer::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::PointBuffer"))
        return static_cast<void*>(const_cast<PointBuffer*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll___Instruction[] = {

 // content:
    7, // revision
    321,  // classname
    0, 0, // classinfo
    19, 14, // methods
    4, 286, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 109, 2, 5,
    7, 1, 118, 2, 5,
    9, 3, 121, 2, 5,

// slot: name, argc, parameters, tag, flags
    322, 1, 128, 2, 11,
    322, 2, 131, 2, 11,
    322, 3, 136, 2, 11,
    322, 4, 143, 2, 11,
    322, 5, 152, 2, 11,
    322, 6, 163, 2, 11,
    322, 7, 176, 2, 11,
    322, 8, 191, 2, 11,
    322, 9, 208, 2, 11,
    322, 10, 227, 2, 11,
    322, 11, 248, 2, 9,
    334, 0, 271, 2, 9,
    335, 2, 272, 2, 9,
    314, 1, 277, 2, 9,
    316, 1, 280, 2, 9,
    318, 1, 283, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, QMetaType::Int, 323,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330, 331,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333,
    QMetaType::Void,
    QMetaType::QVariant, 0x80000000 | 21, 0x80000000 | 337, 336, 338,
    QMetaType::Void, QMetaType::Int, 315,
    QMetaType::Void, QMetaType::Int, 317,
    QMetaType::Void, QMetaType::Int, 319,

 // properties: name, type, flags
    88, QMetaType::QString, 0x0a055003, 		 // QString control
    315, QMetaType::Int, 0x02015003, 		 // int head
    317, QMetaType::Int, 0x02015003, 		 // int headf
    319, QMetaType::Int, 0x02015003, 		 // int tail

    0 // eod
};

const QMetaObject _Instruction::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll___Instruction, 0, 0, 0 }
};

void *_Instruction::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::_Instruction"))
        return static_cast<void*>(const_cast<_Instruction*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_mccdll__Instruction[] = {

 // content:
    7, // revision
    339,  // classname
    0, 0, // classinfo
    19, 14, // methods
    3, 286, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 109, 2, 5,
    7, 1, 118, 2, 5,
    9, 3, 121, 2, 5,

// slot: name, argc, parameters, tag, flags
    322, 1, 128, 2, 11,
    322, 2, 131, 2, 11,
    322, 3, 136, 2, 11,
    322, 4, 143, 2, 11,
    322, 5, 152, 2, 11,
    322, 6, 163, 2, 11,
    322, 7, 176, 2, 11,
    322, 8, 191, 2, 11,
    322, 9, 208, 2, 11,
    322, 10, 227, 2, 11,
    322, 11, 248, 2, 9,
    334, 0, 271, 2, 9,
    335, 2, 272, 2, 9,
    314, 1, 277, 2, 9,
    316, 1, 280, 2, 9,
    318, 1, 283, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, QMetaType::Int, 323,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330, 331,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333,
    QMetaType::Void,
    QMetaType::QVariant, 0x80000000 | 21, 0x80000000 | 337, 336, 338,
    QMetaType::Void, QMetaType::Int, 315,
    QMetaType::Void, QMetaType::Int, 317,
    QMetaType::Void, QMetaType::Int, 319,

 // properties: name, type, flags
    315, QMetaType::Int, 0x02015003, 		 // int head
    317, QMetaType::Int, 0x02015003, 		 // int headf
    319, QMetaType::Int, 0x02015003, 		 // int tail

    0 // eod
};

const QMetaObject Instruction::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_mccdll__Instruction, 0, 0, 0 }
};

void *Instruction::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "mccdll::Instruction"))
        return static_cast<void*>(const_cast<Instruction*>(this));
    return QAxObject::qt_metacast(_clname);
}

